name: zjucat
appid: rk2are
invokeUrl: https://rk2are.laf.run
function:
  developToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBpZCI6InJrMmFyZSIsInR5cGUiOiJkZXZlbG9wIiwiZXhwIjoxNjk5MDcwMDMzLCJpYXQiOjE2OTg0NjUyMzN9.9Pm775QoW75JKNTTpb0WjjJnaZdS8-kyEw5dgZ3FKIo
  developTokenExpire: 1699070035
storage:
  endpoint: https://oss.laf.run
  accessKeyId: DTSSUF64RBQPT1H5XC43
  accessKeySecret: NSzRt2+FqZLxQxN95NNTNVebeRaKx2PJK4xQCVWP
  sessionToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJEVFNTVUY2NFJCUVBUMUg1WEM0MyIsImV4cCI6MTY5OTA3MDAzMywicGFyZW50IjoicmsyYXJlIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVlYQndMWE4wY3kxbWRXeHNMV2R5WVc1MElpd2lSV1ptWldOMElqb2lRV3hzYjNjaUxDSkJZM1JwYjI0aU9pSnpNem9xSWl3aVVtVnpiM1Z5WTJVaU9pSmhjbTQ2WVhkek9uTXpPam82S2lKOVhYMD0ifQ.dSkBc47h5cZ9Pjroyh9w_x45nUmCxWgEZsRWltGlsFpXbd8kwBPC_mKMDQFCkQIqNZSrEO-h-d5CJV1h_OY03Q
  expire: 1699070035
